# Generated by Django 3.1.6 on 2021-02-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=200, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=150, verbose_name='Электронная почта')),
                ('message', models.TextField(blank=True, verbose_name='Заголовок')),
                ('sign', models.TextField(verbose_name='Согласие на обработку')),
                ('number', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=50, unique=True, verbose_name='Выберите ваш уникальный индефикатор ')),
            ],
        ),
    ]
