# Generated by Django 3.1.6 on 2021-02-12 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=150, verbose_name='Электронная почта')),
                ('user_all', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
